### ISSUE TITLE
Feature Request: "IgnoreDMs" Option?

### ISSUE THREAD

**Issue by wkeiuluf** [ergochat/irc-go#97]
Currently: if you do an `AddCallback("PRIVMSG", ...)` and someone messages a "bot" directly, the bot will process everything within the callback. Seems like an easy way to avoid code repeating would be to add something to `ircevent.Connection{}` like `IgnoreDMs` or some such.

Why you would want this: if you have callbacks that trigger API calls, querying webpages, and other stuff, one will naturally want to add some form of general rate-limiting in the code elsewhere, but it seems like it would be easy for someone to accidentally (or on purpose) just message a bot directly and "silently" burn through API credits or whatever. Extra "silent" since `Params[0]` is the bot itself and a user might not even know what they're doing!

Again: having this "simple" piece built straight into `ircevent.Connection` could help reduce code repetition elsewhere.

---

* Is this kind of request "out of scope" for this project?
* "PRs welcome"?
* "Actually you can just do X and get this yourself easily without adding the same `if` check all over the place"?

**Comment by slingamn** [comment]
I'll consider this, but ircevent is kind of a minimalistic framework by design and this isn't the kind of feature I like to add.

I'm not sure about what "the same if check all over the place" means, though. It seems like this can just be checked once at the top of the single `PRIVMSG` handler?

**Comment by slingamn** [comment]
>The bot sends something to itself

Oh, I get it now. I could add something like `GetReplyTarget(msg ircmsg.Message)` where it returns either `Params[0]` if it's a channel, or the source nick if it's a DM? Detecting channels has some subtleties since `#` is not the only valid channel prefix, but it's doable (the "correct" thing is to read the `CHANTYPES` 005 token).

**Comment by slingamn** [comment]
If the concern is the bot going into an infinite feedback loop, the traditional mitigation for this is to have bots only read PRIVMSG and only send NOTICE (since "bot wars" can happen between multiple bots).

**Comment by slingamn** [comment]
I'll plan to add this in the next release

**Comment by slingamn** [comment]
Done in #105
