### ISSUE TITLE
Feature Request(s): Improve Truncation / Message Splitting?

### ISSUE THREAD

**Issue by ghost** [ergochat/irc-go#98]
At the moment, if you set `AllowTruncation` to `true` (in `ircevent.Connection`, then the message will indeed be truncated, but...

## Problem: Unclear truncation happened in chat
There's no clear indication where the message was sent that the message is being truncated and there might be more. This could be resolved by truncating the message slightly further and adding a suffix like `[…]`, e.g.:

> \<user\> .generateLongParagraph
> 
> \<bot\> As the sun dipped below the horizon, casting a warm, golden hue across the tranquil meadow, a sense of serenity washed over the weary travelers. They had journeyed for days through dense forests and rugged terrain, but now, in this idyllic setting, the world seemed to pause. Birds chirped their evening songs, and a gentle breeze rustled the wildflowers. It was a moment of pure, unadulterated beauty, a reminder that even in the midst of life's challenges, nature […]

## Another Potential Solution: Message Splitting
Another option could be splitting messages. So if it's detected that the message length will be longer than the max allowed bytes, just generate a second one to be sent as well, continuing where the last one left off.

---

* Is this kind of request "out of scope" for this project?
* "PRs welcome"?
* "Actually you can just do X or Y and get this yourself easily!"?

**Comment by slingamn** [comment]
We have an old word wrap implementation that used to be part of Ergo:

https://github.com/ergochat/ergo/blob/0d77315a8d30b916f6a96ac63c8998e24448e6c4/irc/utils/text.go

I'm not sure about pulling it into ircevent. Could you try adding a helper/wrapper in your application code that wraps the text if necessary and sends multiple PRIVMSG?
